## Custom Version 01.02.2026
# Copyright Roman Glos
# Jellyfin (via docker bridge network)
# Wichtig: Jellyfin läuft im gleichen Docker-Netz "media_net", daher direkt per Servicename erreichbar.

server {
    listen 8920 ssl;
    listen [::]:8920 ssl;
    http2 on;

    server_name jellyfin.*;

    include /config/nginx/ssl.conf;

    client_max_body_size 0;

    # Haupt-UI / API
    location / {
        include /config/nginx/proxy.conf;
        proxy_pass http://jellyfin:8096;

        proxy_set_header Range $http_range;
        proxy_set_header If-Range $http_if_range;
    }

    # WebSocket Endpoint (Playback / Live Updates)
    location /socket {
        include /config/nginx/proxy.conf;
        proxy_pass http://jellyfin:8096;

        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection $connection_upgrade;
    }
}
